spring:
  application:
    name: spring-boot-docker-compose
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Paparao@1
    url: jdbc:mysql://localhost:3306/tickets
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
